# -*- coding: utf-8 -*-
"""etl-google cloud

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19tCtkxfQIm4kQFCn3QGL68kRjoPxene8
"""

!pip install google-cloud-bigquery pandas requests

from google.colab import auth
auth.authenticate_user()

import requests
import pandas as pd
from google.cloud import bigquery

products_url = "https://dummyjson.com/products"

products_data = requests.get(products_url).json()

products = pd.json_normalize(products_data["products"])

products.head()

users_url = "https://dummyjson.com/users"

users_data = requests.get(users_url).json()

users = pd.json_normalize(users_data["users"])

users.head()

carts_url = "https://dummyjson.com/carts"

carts_data = requests.get(carts_url).json()

carts = pd.json_normalize(carts_data["carts"])

carts.head()

cart_items_list = []

for cart in carts_data["carts"]:
    for item in cart["products"]:
        cart_items_list.append({
            "cartId": cart["id"],
            "userId": cart["userId"],
            "productId": item["id"],
            "quantity": item["quantity"],
            "price": item["price"],
            "total": item["total"]
        })

cart_items = pd.DataFrame(cart_items_list)

cart_items.head()

client = bigquery.Client(project="etl-joyce")

products.columns = products.columns.str.replace('.', '_', regex=False)

client.load_table_from_dataframe(
    products,
    "etl-joyce.rrhh_dataset.products"
).result()

users.columns = users.columns.str.replace('.', '_', regex=False)

client.load_table_from_dataframe(
    users,
    "etl-joyce.rrhh_dataset.users"
).result()

carts.columns = carts.columns.str.replace('.', '_', regex=False)

client.load_table_from_dataframe(
    carts,
    "etl-joyce.rrhh_dataset.carts"
).result()

client.load_table_from_dataframe(
    cart_items,
    "etl-joyce.rrhh_dataset.cart_items"
).result()